[project]
name = 'Decentralized-Healthcare-Population-Analytics'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.analytics-protocol]
path = 'contracts/analytics-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.data-provider-verification]
path = 'contracts/data-provider-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.insight-distribution]
path = 'contracts/insight-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.population-definition]
path = 'contracts/population-definition.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy-preservation]
path = 'contracts/privacy-preservation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
